import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul style={{ display: "flex", alignItems: "center", justifyContent: "space-around", background: "#037290", color: "#fff" }}>
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/docs">Docs</a>
              </li>
              <li>
                <a href="/login">Login</a>
              </li>
              <li>
                <a href="/register">Register</a>
              </li>
            </ul>
          </nav>
        </header>
        <div style={{ marginTop: "100px",   height: "100vh"}}>
        {children}
        </div>
 
        <footer style={{ display: "flex", alignItems: "center", justifyContent: "space-around", background: "#037290", color: "#fff" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
